apiVersion: v1
kind: Secret
metadata:
  name: postgres
data:
  POSTGRES_PASSWORD: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk  ##my-super-secret-password ###echo -n 'yourpasswordhere' | base64
stringData:
  POSTGRES_USER: root
  
